apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  weather-knative.com: |
    selector:
      app: weather-knative
  svc.cluster.local: |
    selector:
      app: secret
  mydefault.com: ""